[package]
name = "resizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_image_resize = {path=".."}
image = "0.24.2"
clap = { version = "3.2.14", features = ["derive"] }
log = "0.4.17"
env_logger = "0.9.0"
anyhow = "1.0.58"
clap-verbosity-flag = "1.0.1"
