[package]
name = "benches_wasm"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]


[dependencies]
fast_image_resize = { path = "..", features = ["image"] }
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
js-sys = "0.3.103"
image = { version = "0.25.6", default-features = false, features = ["png"] }
resize = { version = "0.8.9", default-features = false, features = ["std"] }
rgb = "0.8.53"
console_error_panic_hook = "0.1.7"
gloo-timers = { version = "0.4.0", features = ["futures"] }


[dependencies.web-sys]
version = "0.3.103"
features = ["Document", "Element", "HtmlElement", "Node", "Window", "Request", "RequestInit", "RequestMode", "Response", "Performance"]


[package.metadata.wasm-pack.profile.release]
wasm-opt = false
