[package]
name = "testing"
version = "0.1.0"
edition = "2021"


[dependencies]
fast_image_resize = { path = "..", features = ["for_testing"] }
image = "0.25.1"


[package.metadata.release]
publish = false
